services:
  web:
    build: .
    container_name: booking_hotels_web
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-super_secret_docker_key_2026}
      # Kita membiarkan file .env menimpa environment DB ini
      - DB_HOST=${DB_HOST:-global_mysql}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-root_password}
      - DB_NAME=${DB_NAME:-hotel_booking}
      - MAIL_SERVER=${MAIL_SERVER:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USE_TLS=${MAIL_USE_TLS:-True}
      - MAIL_USERNAME=${MAIL_USERNAME:-}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER:-noreply@antigravityhotels.com}
    volumes:
      - uploads_data:/app/static/uploads
      - session_data:/app/flask_session
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  uploads_data:
  session_data:
