-- ============================================================
--  Seed Data for Provinces and Cities
--  Total: 34 provinces, 489 cities
-- ============================================================

USE hotel_booking;

-- Insert Provinces
INSERT IGNORE INTO provinces (province_id, province) VALUES ('1', 'NUSA TENGGARA BARAT (NTB)');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('10', 'DKI JAKARTA');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('11', 'BANTEN');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('12', 'JAWA TENGAH');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('13', 'JAMBI');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('14', 'PAPUA');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('15', 'BALI');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('16', 'SUMATERA UTARA');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('17', 'GORONTALO');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('18', 'JAWA TIMUR');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('19', 'DI YOGYAKARTA');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('2', 'MALUKU');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('20', 'SULAWESI TENGGARA');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('21', 'NUSA TENGGARA TIMUR (NTT)');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('22', 'SULAWESI UTARA');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('23', 'SUMATERA BARAT');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('24', 'BANGKA BELITUNG');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('25', 'RIAU');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('26', 'SUMATERA SELATAN');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('27', 'SULAWESI TENGAH');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('28', 'KALIMANTAN BARAT');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('29', 'PAPUA BARAT');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('3', 'KALIMANTAN SELATAN');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('30', 'LAMPUNG');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('31', 'KALIMANTAN UTARA');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('32', 'MALUKU UTARA');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('33', 'SULAWESI SELATAN');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('34', 'SULAWESI BARAT');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('4', 'KALIMANTAN TENGAH');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('5', 'JAWA BARAT');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('6', 'BENGKULU');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('7', 'KALIMANTAN TIMUR');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('8', 'KEPULAUAN RIAU');
INSERT IGNORE INTO provinces (province_id, province) VALUES ('9', 'NANGGROE ACEH DARUSSALAM (NAD)');


-- Insert Cities
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('1', '1', 'MATARAM', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('10', '1', 'SUMBAWA BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('100', '9', 'LHOKSEUMAWE', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('101', '9', 'ACEH BESAR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('102', '9', 'BIREUEN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('104', '9', 'ACEH TENGGARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('106', '9', 'ACEH BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('107', '9', 'PIDIE', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('109', '9', 'ACEH TENGAH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('11', '2', 'AMBON', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('110', '9', 'ACEH SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('111', '9', 'SABANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('112', '9', 'ACEH BARAT DAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('113', '9', 'ACEH JAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('114', '9', 'ACEH SINGKIL', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('116', '9', 'ACEH TAMIANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('117', '9', 'ACEH TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('118', '9', 'ACEH UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('12', '2', 'MALUKU TENGAH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('120', '9', 'BENER MERIAH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('122', '9', 'GAYO LUES', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('124', '9', 'NAGAN RAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('125', '9', 'PIDIE JAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('127', '9', 'SIMEULUE', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('128', '9', 'SUBULUSSALAM', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('129', '5', 'CIREBON', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('131', '5', 'INDRAMAYU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('132', '5', 'KUNINGAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('133', '5', 'MAJALENGKA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('135', '10', 'JAKARTA BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('136', '10', 'JAKARTA SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('137', '10', 'JAKARTA PUSAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('138', '10', 'JAKARTA UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('139', '10', 'JAKARTA TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('14', '2', 'MALUKU TENGGARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('141', '10', 'KEPULAUAN SERIBU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('143', '11', 'CILEGON', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('144', '11', 'PANDEGLANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('147', '11', 'LEBAK', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('148', '11', 'SERANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('149', '12', 'CILACAP', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('15', '2', 'TUAL', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('150', '13', 'JAMBI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('152', '13', 'TANJUNG JABUNG BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('153', '13', 'MERANGIN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('154', '13', 'BATANG HARI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('156', '13', 'BUNGO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('157', '13', 'SUNGAIPENUH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('158', '13', 'KERINCI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('16', '2', 'BURU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('160', '13', 'MUARO JAMBI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('161', '13', 'SAROLANGUN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('163', '13', 'TANJUNG JABUNG TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('164', '13', 'TEBO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('165', '14', 'JAYAPURA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('166', '14', 'BIAK NUMFOR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('167', '14', 'MERAUKE', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('168', '14', 'NABIRE', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('169', '14', 'DOGIYAI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('17', '2', 'BURU SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('171', '14', 'KEPULAUAN YAPEN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('172', '14', 'JAYAWIJAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('174', '14', 'LANNY JAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('175', '14', 'YALIMO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('176', '14', 'NDUGA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('177', '14', 'MAMBERAMO TENGAH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('178', '14', 'ASMAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('180', '14', 'BOVEN DIGOEL', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('181', '14', 'KEEROM', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('183', '14', 'MAPPI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('184', '14', 'INTAN JAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('185', '14', 'PANIAI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('186', '14', 'DEIYAI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('187', '14', 'PEGUNUNGAN BINTANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('188', '14', 'PUNCAK JAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('189', '14', 'PUNCAK', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('19', '2', 'KEPULAUAN ARU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('190', '14', 'SARMI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('192', '14', 'SUPIORI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('193', '14', 'TOLIKARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('195', '14', 'WAROPEN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('196', '14', 'YAHUKIMO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('198', '14', 'MAMBERAMO RAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('199', '5', 'DEPOK', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('2', '1', 'BIMA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('201', '15', 'DENPASAR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('203', '15', 'KARANGASEM', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('204', '15', 'BANGLI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('205', '15', 'GIANYAR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('206', '15', 'JEMBRANA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('208', '15', 'KLUNGKUNG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('21', '2', 'SERAM BAGIAN BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('210', '15', 'BULELENG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('211', '15', 'TABANAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('212', '15', 'BADUNG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('218', '16', 'TOBA SAMOSIR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('219', '16', 'GUNUNGSITOLI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('220', '16', 'NIAS', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('221', '16', 'NIAS BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('222', '16', 'NIAS SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('223', '16', 'NIAS UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('225', '16', 'SIBOLGA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('226', '16', 'TAPANULI TENGAH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('227', '16', 'PADANG SIDEMPUAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('228', '16', 'TAPANULI SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('229', '16', 'TAPANULI UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('23', '2', 'SERAM BAGIAN TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('231', '16', 'PADANG LAWAS UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('239', '16', 'HUMBANG HASUNDUTAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('24', '2', 'MALUKU BARAT DAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('240', '16', 'MANDAILING NATAL', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('243', '16', 'PADANG LAWAS', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('25', '2', 'MALUKU TENGGARA BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('251', '17', 'GORONTALO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('252', '17', 'GORONTALO UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('253', '17', 'BOALEMO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('254', '17', 'BONE BOLANGO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('255', '17', 'POHUWATO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('256', '18', 'JEMBER', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('257', '18', 'BANYUWANGI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('258', '18', 'BONDOWOSO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('259', '19', 'YOGYAKARTA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('260', '19', 'BANTUL', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('261', '19', 'SLEMAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('262', '19', 'KULON PROGO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('263', '19', 'GUNUNG KIDUL', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('264', '20', 'KENDARI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('267', '20', 'BAU-BAU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('268', '20', 'KOLAKA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('269', '20', 'KOLAKA TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('271', '20', 'BUTON UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('272', '20', 'MUNA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('273', '20', 'MUNA BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('276', '20', 'KONAWE', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('277', '20', 'KONAWE UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('280', '20', 'BOMBANA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('281', '20', 'BUTON', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('282', '20', 'BUTON SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('283', '20', 'BUTON TENGAH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('285', '20', 'KOLAKA UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('286', '20', 'KONAWE SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('287', '20', 'WAKATOBI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('288', '20', 'KONAWE KEPULAUAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('289', '18', 'KEDIRI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('29', '3', 'BANJARMASIN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('290', '21', 'KUPANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('292', '21', 'SUMBA TENGAH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('293', '21', 'BELU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('294', '21', 'MALAKA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('296', '21', 'ALOR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('297', '21', 'TIMOR TENGAH UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('298', '21', 'FLORES TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('3', '1', 'DOMPU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('30', '3', 'HULU SUNGAI TENGAH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('300', '21', 'SIKKA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('301', '21', 'MANGGARAI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('308', '21', 'TIMOR TENGAH SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('309', '21', 'ENDE', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('310', '21', 'NGADA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('313', '21', 'SUMBA TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('314', '21', 'SUMBA BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('318', '21', 'MANGGARAI BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('319', '21', 'MANGGARAI TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('32', '3', 'HULU SUNGAI SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('321', '21', 'NAGEKEO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('323', '21', 'ROTE NDAO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('325', '21', 'SUMBA BARAT DAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('326', '21', 'LEMBATA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('328', '21', 'SABU RAIJUA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('329', '5', 'KARAWANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('330', '22', 'MANADO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('331', '22', 'KOTAMOBAGU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('332', '22', 'BOLAANG MONGONDOW UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('333', '22', 'BOLAANG MONGONDOW', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('335', '22', 'BOLAANG MONGONDOW SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('336', '22', 'BOLAANG MONGONDOW TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('338', '22', 'KEPULAUAN SANGIHE', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('339', '22', 'KEPULAUAN SIAU TAGULANDANG BIARO (SITARO)', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('34', '3', 'KOTABARU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('341', '22', 'MINAHASA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('342', '22', 'BITUNG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('347', '22', 'KEPULAUAN TALAUD', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('348', '22', 'MINAHASA UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('349', '22', 'MINAHASA SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('35', '3', 'TABALONG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('351', '22', 'MINAHASA TENGGARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('352', '22', 'TOMOHON', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('353', '18', 'MADIUN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('355', '18', 'MAGETAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('357', '18', 'NGAWI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('359', '18', 'PACITAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('36', '3', 'BANJARBARU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('360', '18', 'PONOROGO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('361', '16', 'MEDAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('363', '16', 'ASAHAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('364', '16', 'DAIRI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('365', '16', 'DELI SERDANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('366', '16', 'BINJAI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('368', '16', 'SIMALUNGUN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('370', '16', 'LABUHANBATU UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('371', '16', 'LABUHANBATU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('372', '16', 'LABUHANBATU SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('374', '16', 'KARO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('375', '16', 'LANGKAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('376', '16', 'SERDANG BEDAGAI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('377', '16', 'TEBING TINGGI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('378', '16', 'BATU BARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('379', '16', 'PAKPAK BHARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('38', '3', 'HULU SUNGAI UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('380', '16', 'SAMOSIR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('381', '16', 'TANJUNG BALAI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('382', '16', 'PEMATANG SIANTAR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('383', '12', 'MAGELANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('384', '12', 'KEBUMEN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('385', '12', 'WONOSOBO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('386', '12', 'PURWOREJO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('387', '12', 'TEMANGGUNG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('388', '18', 'MOJOKERTO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('389', '18', 'JOMBANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('39', '3', 'BARITO KUALA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('390', '18', 'NGANJUK', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('391', '18', 'MALANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('392', '18', 'BLITAR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('393', '18', 'BATU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('394', '18', 'PROBOLINGGO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('395', '18', 'LUMAJANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('396', '18', 'SITUBONDO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('397', '23', 'PADANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('399', '23', 'TANAH DATAR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('4', '1', 'LOMBOK TENGAH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('40', '3', 'BANJAR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('401', '23', 'BUKITTINGGI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('402', '23', 'PASAMAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('404', '23', 'PESISIR SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('405', '23', 'PARIAMAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('406', '23', 'PADANG PARIAMAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('407', '23', 'LIMA PULUH KOTA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('408', '23', 'PAYAKUMBUH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('410', '23', 'SAWAH LUNTO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('411', '23', 'SOLOK', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('412', '23', 'PADANG PANJANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('413', '23', 'DHARMASRAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('416', '23', 'KEPULAUAN MENTAWAI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('419', '23', 'PASAMAN BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('42', '3', 'TANAH LAUT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('424', '23', 'SOLOK SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('426', '23', 'SIJUNJUNG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('427', '23', 'AGAM', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('428', '24', 'PANGKAL PINANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('429', '24', 'BANGKA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('430', '24', 'BANGKA BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('431', '24', 'BANGKA TENGAH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('432', '24', 'BANGKA SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('433', '25', 'PEKANBARU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('434', '25', 'DUMAI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('435', '25', 'KAMPAR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('436', '25', 'BENGKALIS', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('438', '25', 'INDRAGIRI HULU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('439', '25', 'INDRAGIRI HILIR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('44', '3', 'TAPIN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('441', '25', 'ROKAN HILIR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('443', '25', 'KUANTAN SINGINGI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('444', '25', 'PELALAWAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('447', '25', 'ROKAN HULU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('451', '25', 'SIAK', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('454', '25', 'KEPULAUAN MERANTI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('456', '4', 'PALANGKA RAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('458', '4', 'KATINGAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('46', '4', 'BARITO UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('460', '4', 'KAPUAS', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('462', '4', 'GUNUNG MAS', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('464', '4', 'SERUYAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('466', '4', 'KOTAWARINGIN BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('468', '4', 'KOTAWARINGIN TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('470', '4', 'LAMANDAU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('471', '4', 'PULANG PISAU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('472', '4', 'SUKAMARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('473', '26', 'PALEMBANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('475', '26', 'MUSI RAWAS', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('476', '26', 'MUSI RAWAS UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('479', '26', 'OGAN KOMERING ULU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('48', '4', 'BARITO TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('480', '26', 'OGAN KOMERING ILIR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('482', '26', 'LAHAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('485', '26', 'MUARA ENIM', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('486', '26', 'PENUKAL ABAB LEMATANG ILIR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('487', '26', 'PAGAR ALAM', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('488', '26', 'PRABUMULIH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('489', '26', 'MUSI BANYUASIN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('491', '26', 'BANYUASIN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('492', '26', 'EMPAT LAWANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('493', '26', 'OGAN ILIR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('494', '26', 'OGAN KOMERING ULU TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('495', '26', 'OGAN KOMERING ULU SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('496', '26', 'LUBUK LINGGAU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('497', '27', 'PALU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('498', '27', 'BANGGAI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('499', '27', 'POSO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('5', '1', 'LOMBOK TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('50', '4', 'MURUNG RAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('500', '27', 'TOLI-TOLI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('501', '27', 'BANGGAI LAUT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('502', '27', 'BANGGAI KEPULAUAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('504', '27', 'BUOL', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('505', '27', 'DONGGALA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('507', '27', 'SIGI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('509', '27', 'MOROWALI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('510', '27', 'MOROWALI UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('511', '27', 'PARIGI MOUTONG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('512', '27', 'TOJO UNA-UNA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('513', '28', 'PONTIANAK', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('514', '28', 'KETAPANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('515', '28', 'SANGGAU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('516', '28', 'SINGKAWANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('517', '28', 'SINTANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('519', '28', 'KAPUAS HULU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('52', '4', 'BARITO SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('522', '28', 'BENGKAYANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('523', '28', 'LANDAK', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('524', '28', 'MELAWI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('526', '28', 'MEMPAWAH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('527', '28', 'KUBU RAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('528', '28', 'SAMBAS', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('529', '28', 'SEKADAU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('53', '3', 'BALANGAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('530', '28', 'KAYONG UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('531', '18', 'PASURUAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('532', '5', 'PURWAKARTA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('533', '5', 'SUBANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('534', '7', 'SAMARINDA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('536', '7', 'KUTAI BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('537', '7', 'MAHAKAM ULU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('538', '5', 'SUKABUMI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('539', '12', 'SURAKARTA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('54', '3', 'TANAH BUMBU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('540', '12', 'BOYOLALI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('541', '12', 'KARANGANYAR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('542', '12', 'KLATEN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('543', '12', 'SRAGEN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('544', '12', 'SUKOHARJO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('545', '12', 'WONOGIRI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('546', '29', 'SORONG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('547', '29', 'TAMBRAUW', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('548', '29', 'FAKFAK', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('549', '29', 'KAIMANA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('55', '5', 'BANDUNG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('551', '29', 'RAJA AMPAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('552', '29', 'SORONG SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('553', '29', 'MAYBRAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('554', '29', 'TELUK BINTUNI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('556', '29', 'TELUK WONDAMA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('557', '29', 'MANOKWARI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('558', '29', 'PEGUNUNGAN ARFAK', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('559', '29', 'MANOKWARI SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('56', '5', 'CIMAHI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('560', '12', 'SEMARANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('561', '12', 'JEPARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('562', '12', 'KUDUS', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('563', '12', 'PEKALONGAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('564', '12', 'BATANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('565', '12', 'BLORA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('566', '18', 'BOJONEGORO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('567', '12', 'DEMAK', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('568', '12', 'KENDAL', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('569', '12', 'PATI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('57', '5', 'SUMEDANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('570', '12', 'PEMALANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('571', '12', 'GROBOGAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('572', '12', 'REMBANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('573', '12', 'SALATIGA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('575', '12', 'PURBALINGGA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('576', '12', 'BANJARNEGARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('577', '18', 'SURABAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('578', '18', 'GRESIK', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('579', '18', 'LAMONGAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('580', '18', 'BANGKALAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('581', '18', 'PAMEKASAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('582', '18', 'SAMPANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('583', '18', 'SIDOARJO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('584', '18', 'SUMENEP', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('585', '18', 'TUBAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('586', '18', 'TULUNGAGUNG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('587', '18', 'TRENGGALEK', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('588', '12', 'TEGAL', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('589', '12', 'BREBES', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('59', '5', 'GARUT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('591', '12', 'BANYUMAS', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('592', '11', 'TANGERANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('594', '11', 'TANGERANG SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('595', '14', 'MIMIKA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('596', '24', 'BELITUNG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('597', '24', 'BELITUNG TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('598', '30', 'BANDAR LAMPUNG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('599', '30', 'LAMPUNG SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('60', '5', 'BANDUNG BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('600', '30', 'LAMPUNG UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('601', '30', 'METRO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('603', '30', 'LAMPUNG BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('604', '30', 'PESISIR BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('605', '30', 'LAMPUNG TENGAH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('607', '30', 'LAMPUNG TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('608', '30', 'WAY KANAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('609', '30', 'TULANG BAWANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('610', '30', 'MESUJI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('611', '30', 'TULANG BAWANG BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('615', '30', 'PRINGSEWU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('616', '30', 'TANGGAMUS', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('618', '30', 'PESAWARAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('619', '8', 'TANJUNG PINANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('62', '5', 'CIANJUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('624', '8', 'BINTAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('626', '31', 'TARAKAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('627', '31', 'BULUNGAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('628', '31', 'MALINAU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('629', '31', 'NUNUKAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('63', '5', 'BEKASI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('631', '31', 'TANA TIDUNG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('632', '5', 'TASIKMALAYA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('633', '5', 'BANJAR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('634', '5', 'CIAMIS', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('635', '5', 'PANGANDARAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('636', '32', 'TERNATE', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('637', '32', 'HALMAHERA BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('639', '32', 'HALMAHERA SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('64', '6', 'BENGKULU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('640', '32', 'HALMAHERA TENGAH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('641', '32', 'HALMAHERA TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('642', '32', 'HALMAHERA UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('643', '32', 'PULAU MOROTAI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('644', '32', 'KEPULAUAN SULA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('646', '32', 'PULAU TALIABU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('647', '32', 'TIDORE KEPULAUAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('648', '33', 'MAKASSAR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('649', '33', 'BANTAENG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('65', '6', 'BENGKULU UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('650', '33', 'BARRU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('651', '33', 'BULUKUMBA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('652', '33', 'ENREKANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('653', '33', 'JENEPONTO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('654', '33', 'TANA TORAJA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('655', '33', 'TORAJA UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('657', '34', 'MAMUJU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('658', '34', 'MAMUJU TENGAH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('659', '33', 'MAROS', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('66', '6', 'BENGKULU TENGAH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('662', '34', 'MAJENE', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('663', '33', 'PALOPO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('664', '33', 'PINRANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('665', '34', 'POLEWALI MANDAR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('667', '33', 'SIDENRENG RAPPANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('67', '6', 'REJANG LEBONG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('670', '33', 'WAJO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('671', '33', 'SINJAI', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('673', '33', 'GOWA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('674', '33', 'TAKALAR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('676', '33', 'BONE', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('678', '33', 'SOPPENG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('679', '33', 'KEPULAUAN SELAYAR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('68', '6', 'BENGKULU SELATAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('680', '33', 'PANGKAJENE KEPULAUAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('683', '33', 'PAREPARE', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('684', '33', 'LUWU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('685', '33', 'LUWU TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('686', '33', 'LUWU UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('687', '34', 'MAMASA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('688', '34', 'MAMUJU UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('69', '6', 'KAUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('7', '1', 'SUMBAWA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('70', '6', 'KEPAHIANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('71', '6', 'LEBONG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('73', '6', 'MUKO MUKO', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('76', '6', 'SELUMA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('77', '5', 'BOGOR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('78', '7', 'BALIKPAPAN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('79', '7', 'KUTAI KARTANEGARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('8', '1', 'LOMBOK BARAT', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('80', '7', 'PASER', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('81', '7', 'BERAU', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('83', '7', 'PENAJAM PASER UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('84', '7', 'BONTANG', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('86', '7', 'KUTAI TIMUR', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('9', '1', 'LOMBOK UTARA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('90', '8', 'BATAM', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('92', '8', 'LINGGA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('94', '8', 'NATUNA', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('95', '8', 'KEPULAUAN ANAMBAS', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('96', '8', 'KARIMUN', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('97', '9', 'BANDA ACEH', '', '');
INSERT IGNORE INTO cities (city_id, province_id, city_name, type, postal_code) VALUES ('98', '9', 'LANGSA', '', '');
