name: Auto Deploy to VPS (Self-Hosted Runner)

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy Application
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Rebuild and Restart Docker Containers
        run: |
          # Kopi file .env rahasia dari brankas VPS ke folder proyek ini
          cp /var/www/secrets/booking-hotels.env .env
          
          # Takedown old containers
          docker compose down
          
          # Build and start new containers
          docker compose up -d --build
          
          # Cleanup unused docker images to save space
          docker image prune -f
